version: "3.4"

services:
  fipu-praksa-frontend:
    image: lukablaskovic/fp-fipu-internship-frontend
    container_name: fipu-praksa-frontend
    volumes:
      - fipu-praksa-frontend_build:/app/dist
    networks:
      - app-network
    expose:
      - "4000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8085:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/fipu-praksa.unipu.hr:/etc/letsencrypt/live/fipu-praksa.unipu.hr
      - /etc/letsencrypt/archive/fipu-praksa.unipu.hr:/etc/letsencrypt/archive/fipu-praksa.unipu.hr
      - /etc/letsencrypt/live/fipubot.unipu.hr:/etc/letsencrypt/live/fipubot.unipu.hr
      - /etc/letsencrypt/archive/fipubot.unipu.hr:/etc/letsencrypt/archive/fipubot.unipu.hr
      - /etc/letsencrypt/live/baserow.unipu.hr:/etc/letsencrypt/live/baserow.unipu.hr
      - /etc/letsencrypt/archive/baserow.unipu.hr:/etc/letsencrypt/archive/baserow.unipu.hr
    depends_on:
      - fipu-praksa-frontend
      - baserow-db
    networks:
      - app-network

  python-bpmn-engine:
    image: lukablaskovic/fp-python-bpmn-engine
    env_file:
      - .env
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - POSTGRES_PROVIDER=${POSTGRES_PROVIDER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB1_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - BASEROW_CONNECTOR_URL=${BASEROW_CONNECTOR_URL}
      - SENDGRID_CONNECTOR_URL=${SENDGRID_CONNECTOR_URL}
      - PDF_CONNECTOR_URL=${PDF_CONNECTOR_URL}
      - BUGSNAG=${PBE_BUGSNAG}
      - PORT=${PBE_PORT}
    depends_on:
      - postgres-db
      - baserow-db
    expose:
      - "8080"
    networks:
      - app-network

gateway-api:
    image: lukablaskovic/fp-internship-gateway-api
    env_file:
      - .env
    environment:
      - BASEROW_CONNECTOR_URL=${BASEROW_CONNECTOR_URL}
      - BPMN_ENGINE_URL=${BPMN_ENGINE_URL}
      - POSTGRES_HOSTNAME=${POSTGRES_HOST}
      - POSTGRES_DB_NAME=${POSTGRES_DB2_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - PASS_HASHING_ALGORITHM=${PASS_HASHING_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REMEMBER_ME_EXPIRE_MINUTES=${REMEMBER_ME_EXPIRE_MINUTES}
      - SECRET_KEY=${SECRET_KEY}
      - BUGSNAG=${FIGA_BUGSNAG}
      - PORT=${FIGA_PORT}
      - DEBUG=1
    depends_on:
      - postgres-db
      - baserow-db
    expose:
      - "8081"
    networks:
      - app-network

  baserow-connector:
    image: lukablaskovic/fp-baserow-connector-service
    env_file:
      - .env
    environment:
      - BASEROW_TOKEN=${BASEROW_TOKEN}
      - BASE_URL=${BASEROW_BASE_URL}
      - BUGSNAG=${BCS_BUGSNAG}
      - PORT=${BCS_PORT}
      - DEBUG=1

    depends_on:
      - postgres-db
      - baserow-db
    expose:
      - "8082"
    networks:
      - app-network

sendgrid-connector:
    image: lukablaskovic/fp-sendgrid-connector-service
    env_file:
      - .env
    environment:
      - API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - MENTOR_SEND_PDF_TEMPLATE=${MENTOR_SEND_PDF_TEMPLATE}
      - POSLODAVAC_AFTER_ALLOCATION_NOTIFICATION_TEMPLATE=${POSLODAVAC_AFTER_ALLOCATION_NOTIFICATION_TEMPLATE}
      - STUDENT_AFTER_ALLOCATION_NOTIFICATION_TEMPLATE=${STUDENT_AFTER_ALLOCATION_NOTIFICATION_TEMPLATE}
      - STUDENT_AFTER_APPROVAL_TEMPLATE=${STUDENT_AFTER_APPROVAL_TEMPLATE}
      - STUDENT_AFTER_REFUSAL_TEMPLATE=${STUDENT_AFTER_REFUSAL_TEMPLATE}
      - STUDENT_AFTER_RETURN_TEMPLATE=${STUDENT_AFTER_RETURN_TEMPLATE}
      - STUDENT_SEND_PDF_TEMPLATE=${STUDENT_SEND_PDF_TEMPLATE}
      - BUGSNAG=${SCS_BUGSNAG}
      - PORT=${SCS_PORT}
    depends_on:
      - postgres-db
      - baserow-db
    expose:
      - "8083"
    networks:
      - app-network

  pdf-connector:
    image: lukablaskovic/fp-pdf-connector-service
    env_file:
      - .env
    environment:
      - PORT=${PCS_PORT}
      - SERVICE_URL=${PCS_SERVICE_URL}
      - BUGSNAG=${PCS_BUGSNAG}
    depends_on:
      - postgres-db
      - baserow-db
    expose:
      - "8084"
    networks:
      - app-network
      
  baserow-db:
    image: baserow/baserow:1.20.2
    env_file:
      - .env
    environment:
      - BASEROW_PUBLIC_URL=${BASEROW_PUBLIC_URL}
      - BASEROW_EXTRA_ALLOWED_HOSTS=${BASEROW_EXTRA_ALLOWED_HOSTS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    expose:
      - "80"
    volumes:
      - ./volumes/baserow:/baserow/data
    networks:
      - app-network

  postgres-db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    command: -p 5432
    networks:
      - app-network

volumes:
  fipu-praksa-frontend_build:


networks:
  app-network: